#include <fcntl.h>
#include <unistd.h>

#include <cerrno>
#include <cstdio>
#include <iostream>
#include <stdexcept>
#include <string>
#include <system_error>
#include <utility>

namespace {
bool cleanup_failed = false;

[[noreturn]] void fail_errno(const char* operation) {
  throw std::system_error(errno, std::generic_category(), operation);
}

void require(bool condition, const char* message) {
  if (!condition) {
    throw std::runtime_error(message);
  }
}

class UniqueFd {
 public:
  explicit UniqueFd(int fd) : fd_(fd) {
    if (fd_ < 0) {
      fail_errno("open/dup");
    }
  }
  UniqueFd(const UniqueFd&) = delete;
  UniqueFd& operator=(const UniqueFd&) = delete;
  UniqueFd(UniqueFd&& other) noexcept : fd_(std::exchange(other.fd_, -1)) {
  }
  UniqueFd& operator=(UniqueFd&&) = delete;

  ~UniqueFd() {
    if (fd_ >= 0 && ::close(fd_) != 0) {
      // 析构不能抛异常；保留错误并让程序最终失败，不盲目重试close。
      std::perror("close during cleanup");
      cleanup_failed = true;
    }
  }

  int get() const noexcept {
    return fd_;
  }

  void close_checked() {
    // fd编号可能被后续open复用；转移所有权后只执行一次close。
    const int old = std::exchange(fd_, -1);
    if (old >= 0 && ::close(old) != 0) {
      fail_errno("close");
    }
  }

 private:
  int fd_;
};

std::string read_exact(int fd, std::size_t count) {
  std::string data(count, '\0');
  std::size_t done = 0;
  while (done < count) {
    const ssize_t n = ::read(fd, data.data() + done, count - done);
    if (n < 0) {
      if (errno == EINTR) {
        continue;
      }
      fail_errno("read");
    }
    require(n != 0, "unexpected EOF: use the fixture generated by run.sh");
    done += static_cast<std::size_t>(n);
  }
  return data;
}

void rewind_checked(int fd) {
  if (::lseek(fd, 0, SEEK_SET) == static_cast<off_t>(-1)) {
    fail_errno("lseek");
  }
}

void observe(const char* path) {
  UniqueFd first(::open(path, O_RDONLY));
  UniqueFd duplicate(::dup(first.get()));
  UniqueFd independent(::open(path, O_RDONLY));

  // dup复用内核中的打开状态；再次open同一路径产生独立文件偏移。
  require(first.get() != duplicate.get(), "dup must allocate another descriptor");
  const auto a = read_exact(first.get(), 2);
  const auto b = read_exact(duplicate.get(), 2);
  const auto c = read_exact(independent.get(), 2);
  require(a == "AB" && b == "CD" && c == "AB", "unexpected shared offset semantics");
  std::cout << "PASS shared_offset first=" << a << " dup=" << b << " independent_open=" << c
            << '\n';

  first.close_checked();
  const auto d = read_exact(duplicate.get(), 2);
  require(d == "EF", "closing one descriptor invalidated its duplicate");
  std::cout << "PASS close_one_keeps_duplicate=" << d << '\n';

  // C++所有权移动不会调用dup，也不会增加内核引用；旧包装器变为空。
  UniqueFd moved(std::move(duplicate));
  require(duplicate.get() == -1, "move must empty the source owner");
  require(read_exact(moved.get(), 2) == "GH", "moved descriptor changed position");
  char byte = 0;
  ssize_t n;
  do {
    n = ::read(moved.get(), &byte, 1);
  } while (n < 0 && errno == EINTR);
  if (n < 0) {
    fail_errno("read EOF");
  }
  require(n == 0, "expected EOF after eight bytes");
  std::cout << "PASS move_ownership_and_EOF\n";

  errno = 0;
  require(::read(-1, &byte, 1) == -1 && errno == EBADF, "invalid fd must fail with EBADF");
  std::cout << "PASS invalid_fd_EBADF\n";

  // 注入一次作用域异常，检查析构关闭；期间单线程且不分配其他FD，避免编号复用干扰。
  int retired = -1;
  try {
    UniqueFd scoped(::dup(independent.get()));
    retired = scoped.get();
    throw std::runtime_error("injected scope exit");
  } catch (const std::runtime_error&) {
    require(retired >= 0, "injection must happen after successful dup");
  }
  errno = 0;
  require(::fcntl(retired, F_GETFD) == -1 && errno == EBADF,
          "RAII did not close the descriptor during exception unwinding");
  rewind_checked(independent.get());
  require(read_exact(independent.get(), 2) == "AB", "surviving owner is unusable");
  std::cout << "PASS exception_cleanup_and_surviving_owner\n";

  moved.close_checked();
  independent.close_checked();
}
}  // namespace

int main(int argc, char** argv) {
  if (argc != 2) {
    std::cerr << "usage: fd_observe <8-byte ABCDEFGH fixture>\n";
    return 2;
  }
  try {
    observe(argv[1]);
    require(!cleanup_failed, "cleanup reported an error");
    std::cout << "ALL CHECKS PASSED; host OS semantics only; no performance claim\n";
    return 0;
  } catch (const std::exception& error) {
    std::cerr << "FAIL: " << error.what() << '\n';
    return 1;
  }
}
